---
- name: Set Rsyslog facts then include rsyslog role
  block:

    - name: Set rsyslog_enabled
      set_fact:
        rsyslog_enabled: "{{ logging_enabled | d(true) }}"

    - name: Set rsyslog_output_elasticsearch for the omelasticsearch output
      set_fact:
        rsyslog_output_elasticsearch: "{{ rsyslog_output_elasticsearch | d([]) }} + {{ [ item ] }}"
      loop: "{{ logging_outputs }}"
      when:
        - item.name is defined
        - item.type | d('') == 'elasticsearch'

    - name: Set rsyslog_output_files for the omfile outputs
      set_fact:
        rsyslog_output_files: "{{ rsyslog_output_files | d([]) }} + {{ [ item ] }}"
      loop: "{{ logging_outputs }}"
      when:
        - item.name is defined
        - item.type | d('') == 'files'

    - name: Set rsyslog_output_forwards for the omfwd output
      set_fact:
        rsyslog_output_forwards: "{{ rsyslog_output_forwards | d([]) }} + {{ [ item ] }}"
      loop: "{{ logging_outputs }}"
      when:
        - item.name is defined
        - item.target is defined
        - item.type | d('') == 'forwards'

    - name: Set rsyslog_outputs
      set_fact:
        rsyslog_outputs: '{{ rsyslog_output_elasticsearch | d([]) }} + {{ rsyslog_output_files | d([]) }} + {{ rsyslog_output_forwards | d([]) }}'

    - name: Set files output if logging_output_files is empty and logging_inputs is not empty
      set_fact:
        rsyslog_outputs: '{{ rsyslog_outputs | d([]) }} + [ {"name": "files", "type": "files"} ]'
      when:
        - rsyslog_output_files | d([]) | length == 0
        - logging_inputs | d([])

    - name: Set rsyslog_input_basics
      set_fact:
        rsyslog_input_basics: '{{ rsyslog_input_basics | d([]) }} + {{ [ item ] }}'
      with_items: "{{ logging_inputs }}"
      when:
        - item.name is defined
        - item.type | d('') == 'basics'

    # If there are multiple basics configs are given, report an error
    - name: Check that there is not multiple basics input is configured
      assert:
        that: rsyslog_input_basics | d([]) | length <= 1

    - name: Set rsyslog_input_files
      set_fact:
        rsyslog_input_files: "{{ rsyslog_input_files | d([]) }} + {{ [ item ] }}"
      with_items: "{{ logging_inputs }}"
      when:
        - item.name is defined
        - item.type | d('') == 'files'

    - name: Set rsyslog_input_ovirt
      set_fact:
        rsyslog_input_ovirt: "{{ rsyslog_input_ovirt | d([]) }} + {{ [ item ] }}"
      with_items: "{{ logging_inputs }}"
      when:
        - item.name is defined
        - item.type | d('') == 'ovirt'

    - name: Set rsyslog_input_viaq
      set_fact:
        rsyslog_input_viaq: "{{ rsyslog_input_viaq | d([]) }} + {{ [ item ] }}"
      with_items: "{{ logging_inputs }}"
      when:
        - item.name is defined
        - item.type | d('') == 'viaq'

    - name: Set rsyslog_flows
      set_fact:
        rsyslog_flows: "{{ rsyslog_flows | d([]) }} + {{ [ item ] }}"
      with_items: "{{ logging_flows }}"
      when:
        - item.name is defined
        - item.inputs | d('[]')
        - item.outputs | d('[]')

    - name: Set rsyslog_purge_original_conf fact to purge all configuration files before saving the new ones.
      set_fact:
        rsyslog_purge_original_conf: yes
      when: logging_purge_confs | d(false)

    - name: Set custom_config_files fact
      set_fact:
        rsyslog_custom_config_files: "{{ item.custom_config_files }}"
      with_items: "{{ logging_outputs }}"
      when:
        - item.type | d('') == 'custom'
        - logging_enabled | d(true)

    - name: Re-read facts after adding custom fact
      setup:
        filter: ansible_local
      when: logging_debug | d(false)

    - name: Create rsyslog debug dir
      file:
        path: "{{ role_path }}/debug"
        state: directory
        mode: 0700
      when: logging_debug | d(false)

    - name: Delete debug file
      file:
        path: "{{ role_path }}/debug/main.yml"
        state: absent
      ignore_errors: true
      when: logging_debug | d(false)

    - name: Create rsyslog debug file
      lineinfile:
        path: "{{ role_path }}/debug/main.yml"
        create: yes
        line: "#ANSIBLE MANAGED VARIABLES FILE"
      when: logging_debug | d(false)

    - name: Populate rsyslog debug file
      lineinfile:
        path: "{{ role_path }}/debug/main.yml"
        create: yes
        line: "{{ item.key }}: {{ item.value | d() | to_nice_json(indent=2) }}"
      with_dict: "{{ hostvars[inventory_hostname] }}"
      when:
        - item.key is match("rsyslog*")
        - logging_debug | d(false)

    - name: Include Rsyslog role
      include_role:
        name: "{{ role_path }}/roles/rsyslog"

  when: logging_collector | d('rsyslog') == 'rsyslog'
