---
# Deploy configuration files
- name: Remove input files example config files from rsyslog.d
  vars:
    __rsyslog_rules: "{{ __rsyslog_files_input_rules }}"
  include_tasks:
    file: files_cleanup.yml
